const fetchMockData = () => Promise.resolve([
    {
        "date": "2025-07-20T04:00:00.000Z",
        "time": "11 AM",
        "heading": "The Imitation of Christ",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "https://www.eventbrite.com/e/1284238494909?aff=oddtdtcreator",
        "status": "",
        "event_type": "SUNDAY"
    },
    {
        "date": "2025-07-22T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Gospel of Sri Ramakrishna",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "",
        "registration_line": "In-person only. No registration.",
        "registration_link": "",
        "status": "",
        "event_type": "GOSPEL"
    },
    {
        "date": "2025-07-25T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Bhagavad Gita",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "",
        "status": "Cancelled",
        "event_type": "GITA"
    },
    {
        "date": "2025-07-27T04:00:00.000Z",
        "time": "11 AM",
        "heading": "II – Philosophies of Doubt and Plain ‘Weird’ Philosophies",
        "subheading": "",
        "speaker": "Massimo Pigliucci, K.D. Irani Professor of Philosophy, The City College of New York",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "https://www.eventbrite.com/e/1284238795809?aff=oddtdtcreator",
        "status": "",
        "event_type": "SUNDAY"
    },
    {
        "date": "2025-07-29T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Gospel of Sri Ramakrishna",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "",
        "registration_line": "In-person only. No registration.",
        "registration_link": "",
        "status": "",
        "event_type": "GOSPEL"
    },
    {
        "date": "2025-08-02T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Bhagavad Gita",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "",
        "status": "Cancelled",
        "event_type": "GITA"
    },
    {
        "date": "2025-08-04T04:00:00.000Z",
        "time": "11 AM",
        "heading": "Unity and Simplicity in Science and\nContemplation",
        "subheading": "",
        "speaker": "Piet Hut, Professor Emeritus, Institute for Advanced Study",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "https://www.eventbrite.com/e/1321910382539?aff=oddtdtcreator",
        "status": "",
        "event_type": "SUNDAY"
    },
    {
        "date": "2025-08-06T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Gospel of Sri Ramakrishna",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "",
        "registration_line": "In-person only. No registration.",
        "registration_link": "",
        "status": "Cancelled",
        "event_type": "GOSPEL"
    },
    {
        "date": "2025-08-09T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Bhagavad Gita",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "https://www.eventbrite.com/e/1332596946339?aff=oddtdtcreator",
        "status": "",
        "event_type": "GITA"
    },
    {
        "date": "2025-08-11T04:00:00.000Z",
        "time": "11 AM",
        "heading": "Ask Swami",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "https://www.eventbrite.com/e/1321910402599?aff=oddtdtcreator",
        "status": "",
        "event_type": "SUNDAY"
    },
    {
        "date": "2025-08-13T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Gospel of Sri Ramakrishna",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "",
        "registration_line": "In-person only. No registration.",
        "registration_link": "",
        "status": "",
        "event_type": "GOSPEL"
    },
    {
        "date": "2025-08-16T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Bhagavad Gita",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "https://www.eventbrite.com/e/1332598290359?aff=oddtdtcreator",
        "status": "",
        "event_type": "GITA"
    },
    {
        "date": "2025-08-18T04:00:00.000Z",
        "time": "11 AM",
        "heading": "Come Home to Yourself: A Journey from Ego to Essence",
        "subheading": "",
        "speaker": "Sadhvi Bhagawati Saraswati, President, Divine Shakti Foundation, Parmarth Niketan, Rishikesh",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "https://www.eventbrite.com/e/1321910422659?aff=oddtdtcreator",
        "status": "",
        "event_type": "SUNDAY"
    },
    {
        "date": "2025-08-20T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Gospel of Sri Ramakrishna",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person only. No registration.",
        "registration_link": "",
        "status": "",
        "event_type": "GOSPEL"
    },
    {
        "date": "2025-08-23T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Bhagavad Gita",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "",
        "registration_line": "In-person by registration only",
        "registration_link": "https://www.eventbrite.com/e/1332599554139?aff=oddtdtcreator",
        "status": "",
        "event_type": "GITA"
    },
    {
        "date": "2025-08-25T04:00:00.000Z",
        "time": "11 AM",
        "heading": "Two Way GPS",
        "subheading": "",
        "speaker": "Swami Anubhavananda Saraswati, The\nSmiling Swami",
        "image": "",
        "youtube_line": "",
        "registration_line": "In-person by registration only",
        "registration_link": "https://www.eventbrite.com/e/1321910462779?aff=oddtdtcreator",
        "status": "",
        "event_type": "SUNDAY"
    },
    {
        "date": "2025-08-27T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Gospel of Sri Ramakrishna",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "",
        "registration_line": "In-person only. No registration.",
        "registration_link": "",
        "status": "Cancelled",
        "event_type": "GOSPEL"
    },
    {
        "date": "2025-08-30T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Bhagavad Gita",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "",
        "registration_line": "In-person by registration only",
        "registration_link": "",
        "status": "Cancelled",
        "event_type": "GITA"
    },
    {
        "date": "2025-09-04T04:00:00.000Z",
        "time": "9 AM",
        "heading": "Kalpataru Day",
        "subheading": "Reading, songs, flower offering",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "",
        "registration_line": "In-person by registration only",
        "registration_link": "",
        "status": "Cancelled",
        "event_type": "FESTIVAL"
    },
    {
        "date": "2025-09-01T04:00:00.000Z",
        "time": "11 AM",
        "heading": "Practical Hints on Meditation",
        "subheading": "",
        "speaker": "Swami Atmajnanananda, Minister-in-charge, Vedanta Center of Greater Washington, D.C.",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "https://www.eventbrite.com/e/1362256910089?aff=oddtdtcreator",
        "status": "",
        "event_type": "SUNDAY"
    },
    {
        "date": "2025-09-03T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Gospel of Sri Ramakrishna",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "",
        "registration_line": "In-person only. No registration.",
        "registration_link": "",
        "status": "",
        "event_type": "GOSPEL"
    },
    {
        "date": "2025-09-06T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Bhagavad Gita",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "https://www.eventbrite.com/e/1363563728819?aff=oddtdtcreator",
        "status": "",
        "event_type": "GITA"
    },
    {
        "date": "2025-09-08T04:00:00.000Z",
        "time": "11 AM",
        "heading": "Vedanta in America: From Emerson to Oppenheimer",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "https://www.eventbrite.com/e/1362256920119?aff=oddtdtcreator",
        "status": "",
        "event_type": "SUNDAY"
    },
    {
        "date": "2025-09-10T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Gospel of Sri Ramakrishna",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "",
        "registration_line": "In-person only. No registration.",
        "registration_link": "",
        "status": "Cancelled",
        "event_type": "GOSPEL"
    },
    {
        "date": "2025-09-13T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Bhagavad Gita",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "",
        "status": "Cancelled",
        "event_type": "GITA"
    },
    {
        "date": "2025-09-15T04:00:00.000Z",
        "time": "11 AM",
        "heading": "Ask Swami",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "https://www.eventbrite.com/e/1362256950209?aff=oddtdtcreator",
        "status": "",
        "event_type": "SUNDAY"
    },
    {
        "date": "2025-09-17T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Gospel of Sri Ramakrishna",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "",
        "registration_line": "In-person only. No registration.",
        "registration_link": "",
        "status": "",
        "event_type": "GOSPEL"
    },
    {
        "date": "2025-09-20T04:00:00.000Z",
        "time": "7:30 PM",
        "heading": "Bhagavad Gita",
        "subheading": "",
        "speaker": "Swami Sarvapriyananda",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "",
        "status": "Cancelled",
        "event_type": "GITA"
    },
    {
        "date": "2025-09-22T04:00:00.000Z",
        "time": "11 AM",
        "heading": "Sri Ramakrishna: The Synthesis of Vedanta",
        "subheading": "",
        "speaker": "Jeffrey Long, Carl W. Zeigler Professor of Religion, Philosophy, and Asian Studies, Elizabethtown College, PA",
        "image": "",
        "youtube_line": "Y",
        "registration_line": "In-person by registration only",
        "registration_link": "https://www.eventbrite.com/e/1362256960239?aff=oddtdtcreator",
        "status": "",
        "event_type": "SUNDAY"
    }
]);